### ISSUE TITLE
[POST] [/power] Body not accepted or value not detected

### ISSUE THREAD

**Issue by Spiritreader** [Walzen-Group/raspmi#2]
When sending a command via rasPMI on the `/power` POST request route it appears that despite specifying `relay-time`, the body is not read properly or the value not accepted

It is still sending the command with a relay time of only 0.1s

Used body:
```json
{ "relay-time": 0.1337 }
```

Feedback: rasPMI: Pressing power button for 0.1 seconds.

**Comment by ykpdang** [comment]
The key is `relay_time` with an underscore and not `relay-time` with a hyphen. Lack of sleep leads to oversights!
